### ISSUE TITLE
requirements.txt missing from manifest, setup.py fails

### ISSUE THREAD

**Issue by payne92** [bjherger/keras-pandas#54]
```
$ pip install keras-pandas
Collecting keras-pandas
  Using cached https://files.pythonhosted.org/packages/b6/4f/cd2e9c9d25024bc76d8806966bc128d4f24e37d7fb64d6ab8f7ed9422601/keras-pandas-1.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v828ze62/keras-pandas/setup.py", line 12, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-v828ze62/keras-pandas/
```

Fails on python 2.7 and 3.5.2

requirements.txt seems to be missing from the tarball.  You probably need to explicitly create a MANIFEST.in to pick it up.

**Comment by bjherger** [comment]
@payne92 Great catch! This should be resolved in #55 . Please give it another shot, and let me know how it goes.

**Comment by payne92** [comment]
Confirmed fixed via `pip install keras-pandas` 

Thanks!
