### ISSUE TITLE
Spaces and parentheses in columns cause "not a valid scope name"

### ISSUE THREAD

**Issue by detly** [bjherger/keras-pandas#83]
If Dataframe column names have spaces or parentheses, the `fit()` function raises an exception:

```python3
import pandas
import keras_pandas.Automater

data_good = pandas.DataFrame({'length': [1.0]})
data_bad = pandas.DataFrame({'length (cm)': [1.0]})

auto_good = keras_pandas.Automater.Automater(numerical_vars=['length'])
auto_bad = keras_pandas.Automater.Automater(numerical_vars=['length (cm)'])

auto_good.fit(data_good)
auto_bad.fit(data_bad)
```

Full traceback:

```text
>>> auto_bad.fit(data_bad)
/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras_pandas/constants.py:33: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  transformed = input_dataframe[variable].as_matrix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras_pandas/Automater.py", line 92, in fit
    input_layers, input_nub = self._create_input_nub(self._variable_type_dict, input_variables_df)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras_pandas/Automater.py", line 272, in _create_input_nub
    variable_input, variable_input_nub_tip = variable_type_handler(variable, input_dataframe)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras_pandas/constants.py", line 42, in input_nub_numeric_handler
    input_layer = keras.Input(shape=(input_sequence_length,), dtype='float32', name='input_{}'.format(variable))
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1745, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5020, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 394, in _apply_op_helper
    with g.as_default(), ops.name_scope(name) as scope:
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6040, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/me/.virtualenvs/p3ml/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4004, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'input_length (cm)' is not a valid scope name
```

I just fell over this using the Iris dataset from Sklearn. If it's an intended constraint it should be documented, but I suspect it's not.

This is using Python 3.6.5, keras-pandas 2.2.0, pandas 0.23.4.

**Comment by bjherger** [comment]
Great catch! The 3.0 version is in the final days of development, so I’ll address this issue in a patch to the 3.0 version, rather than the current 2.X line. 

As an aside, this is a tensorflow restriction in layer names, which can’t be removed. We can, however, internally format variable names to be consistent with tensorflow naming rules. The user wouldn’t know the difference, unless they are poking around in tensorflow objects.

**Comment by bjherger** [comment]
Addressed in #92

**Comment by bjherger** [comment]
@detly Addressed, by converting the 'natural' user provided names into names w/ non-alphanumeric (and underscores) characters removed

**Comment by detly** [comment]
Is this in 3.0.0? I'll work out of `master` for now if not.

**Comment by bjherger** [comment]
@detly This is currently in master, but is not in the release version yet. Working out of master should resolve this issue. 

Long story, but travis is having deploy issues, and I can't (shouldn't?) release new versions until they get their ish together or I move to another CI platform.

**Comment by bjherger** [comment]
@detly JK, variable name formatting is now in 3.0.1, released this morning.
